Docker configuration 81
oaza-waw/rekolekcje-api pull request #97
Opened 2018-06-24 19:38 UTC by KTryCode

Stworzyłem skrypt `./env.sh`, który stawia dwa kontenery PostreSQL. Jeden jest potrzebny, do działania aplikacji, a w drugim siedzi baza danych do testów.
Nie jest to najwydajniejsze rozwiązanie i zostanie ono zoptymalizowane.
Użycie:
`./env.sh start` - postawienie dockerów
`/env.sh wipe` - wyczyszczenie dockerów po skończonej pracy.

Do tego powstał Dockerfile dla `fat-jar'a` (btw. chwilę mi zajęło dojście, dlaczego w ogóle stawia całą aplikację, a nie tylko backend :D) oraz `docker-compose`, który stawia całą aplikację i bazę danych.
Używając `docker-compose up` należy upewnić się, że zaoraliśmy inne kontenery z Postgres: `.env.sh wipe`(będzie konflikt) oraz że nie mamy działającego postgresa `sudo service postgresql status`.
 Nie powinno być konfliktów, ale dmuchajmy na zimne.

Dodatkowo zaktualizowałem README.

Nie skonfigurowałem tworzenia dockerów ze skryptem gradla, ale myślę, że pogadamy o tym, bo mam trochę inna wizję.

2018-06-24 20:51 UTC, qiubix commented on README.md
> +Pamiętaj, że przed wywołaniem testów jednostkowych musi zostać zbudowany
integracyjnych. Tutaj w sumie warto też zaktualizować instrukcję, wydaje mi się, że polecenie `./gradlew test` albo `./gradlew check` powinno odpalić same testy jednostkowe.

2018-06-24 20:53 UTC, qiubix commented on docker-compose.yml
> +      - spring.datasource.url=jdbc:postgresql://rekolekcje-db:5432/rekolekcjedb
czy rekolekcjedb nie mogłoby być tutaj wyznaczane na podstawie POSTGRES_DB? Chodzi mi o to, że jest duplikacja i trzeba tę nazwę zmieniać w dwóch miejscach. Nie znam się za bardzo na docker-compose, ale pewnie można to jakoś zrobić, żeby wyciągać ze zmiennej zamiast podawać explicite.

2018-06-26 12:05 UTC, qiubix requested changes

2018-06-26 12:05 UTC, qiubix commented on README.md
> +`sudo service postgresql stop`
popraw, żeby nie trzeba było ubijać lokalnego postgresa.

2018-06-28 10:54 UTC, qiubix requested changes
Popraw proszę te porty tak, żeby nie rozwalały lokalnych instalacji. Bo jeśli ten commit wejdzie, to np od razu moja konfiguracja, i pewnie innych też, przestanie działać, mimo iż mam poprawnie postawioną bazę. Konfiguracja bezdockerowa powinna działać na domyślnych ustawieniach, natomiast w dockerze możesz sobie poustawiać najróżniejsze customowe porty, bo nas wtedy nie interesuje na jakim porcie to wstanie, skoro wszystko stawia się samo.

2018-06-28 10:54 UTC, qiubix commented on README.md
> +która będzie działać na porcie `localhost:5430` lub skonfigurować aplikację do połączenia z inną bazą.
czemu na porcie 5430, a nie 5432 (domyślnym)?

2018-06-28 10:54 UTC, qiubix commented on rekolekcje-engine/src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5430/rekolekcjedb
zmień port na domyślny. Taki setup utrudnia postawienie aplikacji od zera. Albo trzeba instalować dockera i wtedy wszystko się stawia, ale jak ktoś chce po prostu podpiąć sobie lokalnego postgresa, którego kiedyś sobie zainstalował z domyślnymi ustawieniami, to wtedy jest problem, bo musi kombinować, zamiast po prostu założyć bazę i wystartować aplikację. Konfiguracja portów inna niż domyślna powinna być pozostawiona użytkownikowi, który ma jakiś nietypowy setup.

2018-06-29 19:26 UTC, KTryCode commented on rekolekcje-engine/src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5430/rekolekcjedb
Nie zgadzam się, bo konfiguracja ani trochę nie utrudnia odpalenia środowiska. Skrypt odpala się raz i wszystko jest gotowe. Zbieżne to jest z paradygmatem o prostocie przygotowania aplikacji (R. Martin, "Czysty Kod", rozdział 17.: E1). Chciałbym, żeby `skrypt` stawiał nową , czyściutką bazę danych na porcie, który na 100% nie jest zajęty i aplikacja łączyła się domyślnie z tym portem.
Skrypt odpala kontener dockerowy i binduje go do portu 5430. Nie chciałbym, żebym przez kontener musiał ubijać lokalnego Postgresa.
Zgadzam się oczywiście co do ustawień aplikacji stawianej przez `docker-compose up`.

2018-06-30 16:36 UTC, qiubix commented on rekolekcje-engine/src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5430/rekolekcjedb
ok. Zrób rebase i wrzucimy to :)

2018-07-02 09:55 UTC, qiubix approved these changes

2018-07-02 17:18 UTC, merged